### ISSUE TITLE
In the docs, in `aggregation/index.html`, we should add a table of properties.

### ISSUE THREAD

**Issue by PierreQuinton** [TorchJD/torchjd#102]
This would help the user choosing an appropriate aggregator.

The base could be Table 1 from https://arxiv.org/pdf/2406.16232v1.
We could also add a column that treats convergence to a Pareto optimal point.

**Comment by ValerianRey** [comment]
That would be nice. Can you make a PR for this?

Convergence to a Pareto optiomal would require a lot of work to prove or to disprove though, and would require to specify all the conditions, so I think it's hard to include in a table like this one (at least for now).

**Comment by ValerianRey** [comment]
The table could replace the current listing of aggregators. The hint should also be changed I think, to just say that more details & proofs are available in the paper. And lastly I think we should provide the definitions of the properties at the same place, maybe right below the table (it should be self-contained).
